name: ridelink
description: "A new Flutter project."
 
publish_to: 'none'  
version: 1.0.0+1

environment:
  sdk: ^3.5.4
 
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.2.0
  google_fonts: ^6.2.1
  persistent_bottom_nav_bar: ^6.2.1
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  google_sign_in: ^6.2.2
  shared_preferences: ^2.5.3
  cloud_firestore: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  assets: 
    - assets/images/
    - assets/lottie/
  uses-material-design: true
