// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEcQ4ik3zjz7o-X9bya1OCvEt504IDdKA',
    appId: '1:581668063295:web:b9ec057da9e375399a108a',
    messagingSenderId: '581668063295',
    projectId: 'ridelink-4f465',
    authDomain: 'ridelink-4f465.firebaseapp.com',
    storageBucket: 'ridelink-4f465.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8AorM5kalzTD-iRg65y3YJhGao_eY-a0',
    appId: '1:581668063295:android:db8d07d3d1e626959a108a',
    messagingSenderId: '581668063295',
    projectId: 'ridelink-4f465',
    storageBucket: 'ridelink-4f465.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFBFntZDTc1YHgK2vHQAQG4cJA89fkk5w',
    appId: '1:581668063295:ios:6784268d308aebde9a108a',
    messagingSenderId: '581668063295',
    projectId: 'ridelink-4f465',
    storageBucket: 'ridelink-4f465.firebasestorage.app',
    iosBundleId: 'com.example.ridelink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFBFntZDTc1YHgK2vHQAQG4cJA89fkk5w',
    appId: '1:581668063295:ios:6784268d308aebde9a108a',
    messagingSenderId: '581668063295',
    projectId: 'ridelink-4f465',
    storageBucket: 'ridelink-4f465.firebasestorage.app',
    iosBundleId: 'com.example.ridelink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEcQ4ik3zjz7o-X9bya1OCvEt504IDdKA',
    appId: '1:581668063295:web:cb50041c1d5fac9b9a108a',
    messagingSenderId: '581668063295',
    projectId: 'ridelink-4f465',
    authDomain: 'ridelink-4f465.firebaseapp.com',
    storageBucket: 'ridelink-4f465.firebasestorage.app',
  );

}